### ISSUE TITLE
_answers_file option in copiers.yml is not considered during "copier update"

### ISSUE THREAD

**Issue by sranganathan-deloitte** [copier-org/copier#1035]
**Describe the problem**
I have set `_answers_file: .custom-file.yml` in copier.yml , during the folder creation , the answer file is created as ".custom-file.yml" , but when copier update is executed , it complains with the following error:

`Cannot update because cannot obtain old template references from .copier-answers.yml.`

Appreciate your help.

**Comment by sisp** [comment]
I can reproduce the problem, but after giving it some thought, I think it cannot be solved because there's a :chicken: and :egg: problem. The `copier update` command doesn't receive the template URL but only the project path of the project to be updated. Thus, Copier needs to load the answers file in order to be able to retrieve the template which contains `copier.yml` with the `_answers_file` setting. So it's not possible to get the custom answers file from the `_answers_file` setting before loading the answers file. Do you see the problem?

**Comment by sranganathan-deloitte** [comment]
Oh I get that problem. 
Passing `--answers-file `flag works. Thank you very much for the response.
Also for people who gets to this issue, the command should be in the below order, if you pass --answers-file or --vcs-ref arguments after update , the command will throw error.

`~/venv/copier/bin/copier --answers-file custom_answers_file.yml --vcs-ref=test-branch update `
