### ISSUE TITLE
Force option to copier update

### ISSUE THREAD

**Issue by mitchnegus** [copier-org/copier#1299]
### Describe the problem

The [docs](https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually) seem to suggest that the `copier update` command accepts the `--force` option. 

I'm getting an `Unknown switch --force` error when I try to use that argument, and it doesn't appear to be documented in the `copier update` usage message.

Is this a feature that should exist (and maybe it's a bug that it's not showing up), or just outdated docs? Happy to go do more digging, but I see there seems to have been a decent amount of discussion around updating templates, so figured there might be an obvious (to those who know) reason for the discrepancy.

### To Reproduce

1. Run `copier update --help` and observe that there is no documented `--force` option.

### Expected behavior

Either the `--force` option should exist as the documentation suggests, or the documentation should be reflected to indicate that it has been removed (or never actually existed).

### Operating system

macOS

### Operating system distribution and version

Ventura 13.3.1

### Copier version

copier 8.1.0

### Python version

Python 3.9.6

### Installation method

pip+pypi

**Comment by sisp** [comment]
Thanks for reporting this docs error, @mitchnegus! :pray:

`--force` is an alias for `--overwrite --defaults`. In 6dde037423da28940abeed081d978af621c4ac38, [`copier update` was changed to implicitly use `--overwrite`](https://github.com/copier-org/copier/commit/6dde037423da28940abeed081d978af621c4ac38#diff-5b8fc7eb5ba105f417cced957f2667b945ed4df160a3ee92836ec8f81146f261R358) (and via API, `run_update()` requires `overwrite=True`). At the same time, `--overwrite` was dropped because it became obsolete, and consequently did `--force`.

And thus, you're right that the docs are outdated. I've submitted a PR to update the docs. See #1300.
