### ISSUE TITLE
Have `_commit` in `.copier-answers.yml` always point to the HEAD?

### ISSUE THREAD

**Issue by huxuan** [copier-org/copier#1384]
### Actual Situation

I am developing a template while keeping the generated project in the same repo. I usually test the template with `-r HEAD` which is good, but the painpoint is that the value of `_commit` key in `.copier-answers.yml` always need to change. Especially when I use squash merge, the value is alway invalid after merging the pull request. So I have to ignore the `.copier-answers.yml` currently, but actually, it would be better to keep that to demonstrate how to use `copier update`.

### Desired Situation

Have a copier answer file with `_commit` always point to the HEAD.

### Proposed solution

When rendering template with `-r HEAD`, mark the `_commit` in `.copier-answers.yml` as `HEAD`. When running `copier update`, parse the value the same as `-r HEAD`.

**Comment by huxuan** [comment]
BTW, `HEAD` is not a valid branch name, so it will not be a problem as mention here: https://github.com/copier-org/copier/issues/184#issuecomment-968216418

**Comment by sisp** [comment]
I don't think your suggested solution would work because Copier's update algorithm relies on a stable Git ref for replaying a fresh project creation using the _old_ template version. If `_commit: HEAD` were to be logged, then the Git ref would be ambiguous and the update algorithm wouldn't be able to determine the "old" template version.

I'm not sure I understand your use case of collocating a template and a project generated by that template in the same Git repo. Is this project the only project that uses the template? If so, why do you need a template at all?

**Comment by yajo** [comment]
I guess you do that because it's easy for testing, right? I do the same, but I use https://github.com/KyleKing/copier-template-tester, which was made for that and already works around the problem you're talking about. 

I'll close this issue because I think this will work for you, but feel free to reopen otherwise.

**Comment by huxuan** [comment]
> I don't think your suggested solution would work because Copier's update algorithm relies on a stable Git ref for replaying a fresh project creation using the _old_ template version. If `_commit: HEAD` were to be logged, then the Git ref would be ambiguous and the update algorithm wouldn't be able to determine the old template version.

Thanks for the explanation, I did not think of that problem before.

> I'm not sure I understand your use case of collocating a template and a project generated by that template in the same Git repo. Is this project the only project that uses the template? If so, why do you need a template at all?

Actually, I want to use the generated project with default values as a straightforward demo for the template. Maybe that is not a good choice, I may consider split them in the future.


> I guess you do that because it's easy for testing, right? I do the same, but I use https://github.com/KyleKing/copier-template-tester, which was made for that and already works around the problem you're talking about.
> 
> I'll close this issue because I think this will work for you, but feel free to reopen otherwise.

Thanks for the information, I will look into that. Yes, it is OK to close this issue, since the request is not valid as explained by @sisp.
