### ISSUE TITLE
Allow changing Jinja2 delimiters used in templates

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#1503]
### Actual Situation

We are currently using a Jinja2 script to generate Ansible inventory files. The generated files contain a large number of Jinja2 delimiters, `{{` and `}}`, and there are just a few substitutions done in the template.
We found that the simplest way generate to the inventory files while keeping the template readable, was to change the Jinja2 delimiters in the template.

### Desired Situation

It would be great if `copier` supported changing the delimiters, so that we could switch to copier and simplify the maintenance of the generated inventory files.
Note: Changing delimiters should only be for templates, not the copier config.

### Proposed solution

Copier should support the same (or a subset of) options that can be passed to the Jinja2 `Environment` class.
E.g.:
```
_jinja_options:
  variable_start_string: "<<"
  variable_end_string: ">>"
  ...
```
If some options do not make sense in context of copier, they should generate an error.

**Comment by sisp** [comment]
What about the `_envops` setting? https://copier.readthedocs.io/en/latest/configuring/#envops

> Note: Changing delimiters should only be for templates, not the copier config.

`_envops` applies to template syntax in `copier.yml` though. Why is that a problem for you?

**Comment by lhupfeldt** [comment]
@sisp Thank you for the quick response. I was not aware of this option and did not find it while looking something Jinja related. It seems to be exactly what I need.
I would suggest updating the documentation though, as this i much more usable than just for migration from copier 5. 
Why is it called `_envops`?

**Comment by sisp** [comment]
@lhupfeldt Feel free to submit a PR with docs updates.

> And maybe introduce an option only related to templates, which would probably be really simple because the `_envops` option already exists.

What's the use case for having separate Jinja syntax for `copier.yml` and templates?

> Why is it called `_envops`?

I believe it means "[Jinja] environment options". It has been `_envops` ever since I've seen Copier, so it's probably for historical reasons. `_jinja_options` or `_jinja_env` might have been more intuitive. We could consider adding an alias and eventually deprecate `_envops`. WDYT, @copier-org/maintainers?

**Comment by pawamoy** [comment]
An alias sounds good :+1:

**Comment by lhupfeldt** [comment]
> > And maybe introduce an option only related to templates, which would probably be really simple because the `_envops` option already exists.
> 
> What's the use case for having separate Jinja syntax for `copier.yml` and templates?

Why should the copier config syntax be changed because of a need for special handling of templates?
Using non-standard Jinja2 delimiters is very inconvenient. It is harder for people to understand, maybe less readable, and even worse you have to teach your editor the syntax or give up on any help when editing.
I don't see any reason for changing the config delimiters.
It is also likely that a project might have different templates requiring different delimiters which would be another reason for not linking the config delimiters to those used in templates. Obviously this would require a more complex configuration to be supported, e.g. some annotation in the template file.

**Comment by lhupfeldt** [comment]
> .... We could consider adding an alias and eventually deprecate `_envops`. WDYT, @copier-org/maintainers?
v5 is more than three years old so I think `_envops` can safely be deprecated.

**Comment by pawamoy** [comment]
> Why should the copier config syntax be changed because of a need for special handling of templates?

Because IIRC the same Jinja env is used for both the config file and the templates, so allowing different settings for both would mean a possibly non-trivial refactor, so it needs a good reason for doing it.

> Using non-standard Jinja2 delimiters is very inconvenient.

So you're advocating against the feature you are requesting :sweat_smile:? Have you considered using Jinja's `{% raw %}` tag?

**Comment by lhupfeldt** [comment]
> Because IIRC the same Jinja env is used for both the config file and the templates, so allowing different settings for both would mean a possibly non-trivial refactor, so it needs a good reason for doing it.
> 
I can't disagree with that :grinning: 

> ... IIUC your feature request really is: I want to specify Jinja delimiters _per template_. Did I get that right?

Not necessarily, but I think it might be useful. Let me try to explain our setup:
We have a lot of templates, Maybe 50 times more lines of templates using standard delimiters than using custom delimiters. However, the single template using custom delimiters is expanded using a Jinja2 script, prior to the rest which are handles by Ansible. The custom delimiter template is expanded for each project/customer and becomes the Ansible inventory/host_vars file, which contains a lot of standard delimiters. We are up to 70 projects now, and rising. The problem is that after expanding the inventory template we need to maintain all the expansions as the rest of the setup changes. Then I thought that this is exactly what `copier` does well, so why don't we use copier?
All the expanded config files lives in the same Ansible inventory git repo, so I'm aware that this is not the standard "expand a template and create an new repo" setup, but maybe git submodules could be used to work around that.
 
> ... I think using `{% raw %}` tags can still be readable:

We tried that but using special delimiters was much more readable, I think using the special delimiters in the copier config would be preferable to `raw`. We will have to consider the pros and cons of any necessary changes to move to `copier`, and whether we want to use git submodules.

**Comment by yajo** [comment]
IMHO ˋ_envopsˋ works perfectly fine, and is documented. If you feel we need to improve the docs, then you are totally welcome to open a PR for that! I love it when newcomers PR the docs because this way they get more newbie friendly. Other than that, changing its name just because yes doesn't make much sense to me.

It seems to me like your use case is solved, so I'll close this.

Regarding Ansible, you should also probably take a look at host group variables. They will save you from repeating the same values in your 70 hosts.
