### ISSUE TITLE
Cli Support for _envops and _subdirectory

### ISSUE THREAD

**Issue by bremyozo** [copier-org/copier#1692]
### Actual Situation

The only way currently to change the Jinja environment configuration is using `_envops` https://copier.readthedocs.io/en/stable/configuring/#envops inside `copier.yml` . My use case is having single `copier.yml` file for dynamic template resolution by setting different `_subdirectory` for each template requiring different `_envops` (`variable_start_string`, `variable_end_string`...). The reason `subdirectory` is also needed is that changing only `envops` will break it if templated, thus you can provide new template

Example of current setup

```yaml
_subdirectory: "templates/{{ template }}"

template:
  type: str
  help: Template to use?
  choices:
    template1: null
    template2: null
    ...
```

### Desired Situation

Being able to specify `envops` and `subdirectory` from cli.

### Proposed solution

`Worker` class will need new attributes `envops` and `subdirectory`. Cli subcommands also the same new options and the template should take precedence the config from cli .

**Comment by sisp** [comment]
I'm afraid I don't quite understand your use case. Copier expects one template per Git repository. There may be situations in which it makes sense to dynamically switch between (sub)templates via a templated `_subdirectory` setting in `copier.yml` similar to your sample config above. So, specifying `subdirectory` via CLI is effectively possible via a question as you've shown. Configuring `envops` via CLI doesn't seem to make sense though because this setting is closely related to the template, so runtime-provided `envops` settings would be incompatible with the template. Why do you need to different `envops` settings for the (sub)templates anyway?

**Comment by bremyozo** [comment]
> Why do you need to different envops settings for the (sub)templates anyway?

It's more that the Worker class does not support envops rather than the cli. Let me elaborate

We have an Ansible inventory monorepo with templates for roles, collections, playbooks, hosts... In this case the default jinja envops is also used by the ansible native templating thus there is a need copier templates to use different envops. Each template might also require different envops depending on what what characters need/don't need escaping. Template generation is than handled by a script and also used in CICD, so it needs to support no user interaction. Question-answers are proved in the `data` dict

```python
import copier

...

copier.run_copy(
    src_path=project_path,
    dst_path=dst_path,
    data=data,
    overwrite=overwrite,
    quiet=quiet,
    unsafe=True,
    # envops=jinja_envops,
)
```

All templates are in sub-directories using the same `copier.yml` files as they need the same custom jinja filters, context, shared template includes etc.

> Configuring envops via CLI doesn't seem to make sense though because this setting is closely related to the template, so runtime-provided envops settings would likely be incompatible with the template.

Given that each subdirectory is it's own template, it does make sense for them to have different  runtime-provided envops. Yes, they will be incompatible between each other and that the whole point why you need be able to provide the envops context on runtime


> There may be situations in which it makes sense to dynamically switch between (sub)templates via a templated _subdirectory setting in copier.yml similar to your sample config above. So, specifying subdirectory via CLI is effectively possible via a question as you've shown

To be honest this is more of a workaround than a solution due to the lack of way to do this on runtime

Now thinking about it here are 2 ideas for possible solutions:

## conditional !include

Inspired by the recent `_tasks` update

```yml
_includes:
  - include: path/to/config.yml
    when: "{{ _copier_conf.answers.user.template == 'package' }}"
```

Conditional includes will allow overwriting the runtime context in the yaml config

## Worker class supporting jinja runtime envops

The original proposal to expose runtime envops in the `Worker` class

```python
copier.run_copy(
    envops=jinja_envops_dict,
    subdirectory="/path".
    ...
)
```

**Comment by pawamoy** [comment]
Makes me wonder if one couldn't use the context hook extension to change `self.env` attributes depending on the current context (provided answers).

**Comment by yajo** [comment]
> We have an Ansible inventory monorepo with templates for roles, collections, playbooks, hosts... In this case the default jinja envops is also used by the ansible native templating thus there is a need copier templates to use different envops.

I guess you want Copier to provide a skeleton for your roles, collections, playbooks, because Ansible itself already supports templating and it wouldn't make sense to prefer Copier where Ansible already does a much better job. Then all you need to do is to use a different file extension for each.

Copier uses by default `.jinja`. Thus, every file ended with `.jinja` will be processed by Jinja (by Copier). Do you need to output an Ansible template generated by the Copier template? Then write it to another path such as `ansible-template.j2`, so that Copier does no rendering (even if that file is valid Jinja).

Another option is to specify deliberately different markers for Copier in its `_envops`. Something like this for example: https://github.com/copier-org/copier/blob/b99861d5dd1454a012250fe368d1cbeeb9fcce46/docs/configuring.md?plain=1#L832-L840

That way you can mix the Copier template syntax for render time with standard jinja syntax that will be interpreted by Ansible at run time.

> Given that each subdirectory is it's own template, it does make sense for them to have different runtime-provided envops

This doesn't make sense because they aren't different templates. They are the same template, just rendered from a different subdirectory. But they share everything else, such as the envops or the questionnaire. One example:

```yaml
# copier.yml
_envops:
     variable_end_string: "]]" 
     variable_start_string: "[[" 

_subdirectory: `template-[[ version ]]`

version:
  selection: [1, 2]
  help: For which version of Ansible do you want to render the template?
```

☝🏼 As you see there, to be able to determine the value of `_subdirectory`, you already need a valid envops and an answered questionnaire. Thus, the chosen subdirectory only yields different flavors of the same template, but it won't let you ask different questions (as the questionnaire is already finished) or envops (as the env is already instantiated).

Therefore this is an invalid request AFAICS. Thanks for the report anyways!

**Comment by pawamoy** [comment]
Just to complete my earlier suggestion, try this:

```yaml
_jinja_extensions:
- copier_templates_extensions.TemplateExtensionLoader
- extensions.py:CustomEnvOpsExtension
```

```python
# extensions.py, at the root of your template repo
class CustomEnvOpsExtension(ContextHook):

    def hook(self, context):
        if context["some_answer"] == "some-value":
            self.environment.block_start_string = "((%"
            self.environment.block_end_string = "%))"
            self.environment.variable_start_string = "<<("
            self.environment.variable_end_string = ")>>"
        # elif cases...
        # default case, might not be needed
        else:
            self.environment.block_start_string = "{%"
            self.environment.block_end_string = "%}"
            self.environment.variable_start_string = "{{"
            self.environment.variable_end_string = "}}"
```
