### ISSUE TITLE
Questions are cropped, not wrapped, if the terminal is not wide enough

### ISSUE THREAD

**Issue by abelsiqueira** [copier-org/copier#1764]
### Describe the problem

If the terminal is not wider than the question, the question is cropped. We expected it to be wrapped.

First reported in https://github.com/abelsiqueira/BestieTemplate.jl/issues/422, but reproduced below:

![image](https://github.com/user-attachments/assets/33c0fe64-06a9-41b9-987b-fe6919ca574a)

### Template

https://github.com/abelsiqueira/BestieTemplate.jl

### To Reproduce

```bash
copier copy https://github.com/abelsiqueira/BestieTemplate.jl Tmp.jl
```

### Expected behavior

Long question should be wrapped so fit the width of the terminal.

### Screenshots/screencasts/logs

![image](https://github.com/user-attachments/assets/33c0fe64-06a9-41b9-987b-fe6919ca574a)

![image](https://github.com/user-attachments/assets/70224b7d-0662-4ebd-b590-82501bf0e4ff)

### Operating system

macOS

### Operating system distribution and version

16.1

### Copier version

9.3.1

### Python version

3.12.3

### Installation method

pipx+pypi

**Comment by sisp** [comment]
Thanks for reporting this problem, @abelsiqueira! :pray:

I've been able to reproduce it on Ubuntu 22.04. The problem occurs because the help message ends with `\n` (and a whitespace, but that doesn't matter) to receive the user's answer in the next line. We use the [`questionary`](https://github.com/tmbo/questionary) library for terminal prompting, and it seems the problem is caused either there or further upstream in [`prompt-toolkit`](https://github.com/prompt-toolkit/python-prompt-toolkit):

```python
import questionary

questionary.text(message="UUID (For existing packages, copy the UUID from Project.toml, otherwise use the one generated below)").ask()
# vs.
questionary.text(message="UUID (For existing packages, copy the UUID from Project.toml, otherwise use the one generated below)\n").ask()
```

I've raised an issue in the `questionary` project: https://github.com/tmbo/questionary/issues/398

**Comment by yajo** [comment]
I guess we can close here because, when questionary fixes it and we update, it'll just work, and there's nothing to do here in the mean time, right?
