### ISSUE TITLE
Inconsistency between directories and files names

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#185]
It seems that directories names are rendered even if they don't finish with `.tmpl` (or another given suffix), which I find confusing :slightly_smiling_face:

**Comment by Yajo** [comment]
This is on purpose, because the file could be just copied (not templated) even if the file name itself could be always templated.

I guess if you find this confusing, the best fix would be documenting this properly.

WDYT @pykong? Possibly related to #173.

**Comment by pawamoy** [comment]
> This is on purpose, because the file could be just copied (not templated) even if the file name itself could be always templated.

Ah, so the file/dir name is always rendered, while the contents of a file are only rendered if the name finishes with the given suffix. Got it.

I wonder: what motivated the use of suffixes? A performance motive? Is trying to render every file too CPU intensive or too slow?

**Comment by Yajo** [comment]
I'm not sure... That was a decision already taken when I started contributing.

For me, it makes sense to suffix files because that allows your IDE to highlight Jinja syntax (that's why I configure my templates with normal jinja sintax and `.jinja` suffix).

Another possibility would be that a given file, which includes jinja syntax, is meant to be copied and not templated.

Not sure on the motivation, but TBH it's not disturbing to me and it allows this feature of having a `README.md` file (which belongs to the template) and a `README.md.tmpl` which is meant to be copied. I like that.




> Ah, so the file/dir name is always rendered, while the contents of a file are only rendered if the name finishes with the given suffix. Got it.

So, to recover focus on this issue, the fix would be to clearly document this.

**Comment by pawamoy** [comment]
> For me, it makes sense to suffix files because that allows your IDE to highlight Jinja syntax (that's why I configure my templates with normal jinja sintax and .jinja suffix).

Say no more, I'm buying that :rofl:!

I can see the benefit of the explicit use of a suffix indeed. Thanks for sharing your thoughts!
