### ISSUE TITLE
Docs: draw the logic graph

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#239]
Even after navigating through the code quite some times, I'm still not sure what happens when generating or updating a project.
I think having this graph would help tremendously new users to understand how Copier works, but developers as well, and help a lot when thinking about design and new features implementation.

For example, it would help resolve these issues: #196, #197, #238 and #240.

Of course we should wait for #203, and then maybe use a mermaid-like Markdown extension to draw the graph in the docs 🙂

**Comment by Yajo** [comment]
We have docs now! https://copier.readthedocs.io/en/latest/

These kind of things can now start to get improved, finally!

**Comment by Yajo** [comment]
Would you please tell me if #248 closes this? Or do you think it should be even better explained?

**Comment by pawamoy** [comment]
The docs improvements you made are absolutely great, however I still think a drawing would be very beneficial, both for contributors and users 🙂

**Comment by pawamoy** [comment]
Did I get it right?

![image](https://user-images.githubusercontent.com/3999221/90649974-92ad4c00-e23b-11ea-8c27-90d7bbd748fb.png)

If yes, we can see two issues that were already reported:

1. the diff is done "pre-task" (#196), which by the way makes running the tasks on the temporary project useless
2. tasks are ran again on the current project at the end (#238)

**Comment by Yajo** [comment]
Well, this is only the logic graph for the update system, not for the copy, but it seems quite accurate. There's only one "lie" there:

![imagen](https://user-images.githubusercontent.com/973709/90730188-997da280-e2bf-11ea-861d-dfe6f687cfcf.png)

Because this is not true:



> the diff is done "pre-task" (#196), which by the way makes running the tasks on the temporary project useless

As you can see in the code:

1. Here tasks are run in the tmp copy: https://github.com/copier-org/copier/blob/df33b2953b49449318b776ee072fa9559b49df9a/copier/main.py#L247-L255
1. Here the diff is extracted: https://github.com/copier-org/copier/blob/df33b2953b49449318b776ee072fa9559b49df9a/copier/main.py#L269-L278

**Comment by pawamoy** [comment]
Oh, indeed 😕 Then I'm not sure how I got to this conclusion in #196. I'll have to try and reproduce to debug this.

**Comment by Yajo** [comment]
Yes, that'd be.
