### ISSUE TITLE
Change jinja defaults (breaking change proposal)

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#247]
Hi there, I'm thinking on making a breaking change, undoing copier's choice of using `[[ brackets ]]` instead of `{{ curly braces }}`, to leave just jinja defaults.

I still want to leave that as configurable, but I think many devs can be confused if they don't know Jinja and, after reading the whole docs, things in copier are different.

Also when using an IDE with a Jinja extension, not all of them are configurable.

It would also make templates more familiar for those coming from yeoman or cookiecutter.

I'd be glad to do a major release just to include this change. I find myself changing this setting in all templates and after all modifying them doesn't really add anything useful IMHO.

I want to hear your opinions @pawamoy and @pykong.

TODO:

- [ ] Implement.
- [ ] Document.

**Comment by pawamoy** [comment]
- At first it was confusing yes, many times I made the mistake to use `{{` instead of `[[` and wondered why this wasn't rendered.
- The IDE syntax highlight issues are a bit annoying, yes.
- Using `{{` by default would indeed make it easier to migrate to copier from cookiecutter (I don't know what yeoman is using).

However I still greatly enjoyed that copier is using something else than the usual `{{`, because it makes things so easier when writing templates in templates! My templated projects often contain other Jinja templates, as well as Helm charts which are using go templating and therefore `{{`. Being able to write `{{` without worrying about it getting rendered and surrounding everything with ugly `{% raw %}` statements is nice. Being able to render templates that will again be rendered later, using both `[[` and `{{` is nice as well.

But my use-case is probably not the main use-case, so I agree that using the default `{{` might make more sense for 90% of copier users.

**Comment by benlindsay** [comment]
I work somewhere where cookiecutter is pretty heavily used. Using curly braces instead of brackets would make it easier to convert from cookiecutter to copier, and make it easier for me to convince others to make the change too. I'm in favor of this idea.

Also, can one of you point me to docs on how to configure a project to use curly braces instead of brackets? I see [here](https://copier.readthedocs.io/en/stable/comparisons/) that it says you can configure that, but I'm having trouble finding documentation on actually doing that configuration.

**Comment by Yajo** [comment]
Yes, I was gonna point you there.

Indeed the docs are not helpful right now. I'll revamp them for copier 6, including guidelines on how to make your template work fine on copier 5 and 6, for upgrades.
