### ISSUE TITLE
Remove extra_paths

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#321]
This option is from old and very confusing.

It would allow a template to do things such as `[% extend 'other.tmpl' %]` while `other.tmpl` didn't exist. Besides, it has to indicate a path properly resolvable from the copier execution context (so, a relative path to user's CWD, or absolute path in user's machine, instead of a URL to another template, which could be local or remote).

The amount of buggy cases this feature would produce and the lack of issue reports seems to indicate that nobody uses this. I'll remove it.

If you want to share common templates, the best you can do is to use a git submodule in your template. Copier handles git submodules just fine.

**Comment by tft7000** [comment]
@Yajo : just as a note: this feature was a main reason to look at this project instead of one of the big ones:

- i don't use git (for each template)
- i have a directory setup:
  - fragments/ (template parts)
  - templates/&lt;project templates&gt;/&lt;template that references to different global fragments&gt;

in a ci job i get a template name with an answer file. together I can build a setup for a specific container image. the container that is running the setup job has all the templates and fragments. it will automatically rebuild, if one of the templates changes.

I think it is a petty, if this feature will go, just because there is a potential that a user does not know what he is doing. On the other side, I would prefer support for the configuration directly in copier.yaml.

**Comment by Yajo** [comment]
You can probably solve that by adding a symlink to your fragments folder, right?
