### ISSUE TITLE
bug: copier not deleting a file on update

### ISSUE THREAD

**Issue by joao-p-marques** [copier-org/copier#461]
**Describe the problem**

When you have a file in the template that is rendered depending on a certain variable from copier data, it doesn't get deleted in an update. When you render the template for the first time, it works as expected, but not on an update.

**Template**

The 2 files currently in https://github.com/Tecnativa/doodba-copier-template/tree/main/odoo/custom/build.d should only be rendered if the variable `odoo_version < 11`

(The same happens with https://github.com/OCA/oca-addons-repo-template/issues/77)

**To Reproduce**

1. Run `copier -f -d odoo_version=11 copy gh:Tecnativa/doodba-copier-template .`
2. The 2 files mentioned above are not created, as expected
3. In another folder, run `copier -f -d odoo_version=10 copy gh:Tecnativa/doodba-copier-template .`
4. The 2 files are created, as expected.
5. Run `copier -f -d odoo_version=11 update`
6. The 2 files are not deleted.

**Logs**
You can see here `copier` interprets them as `identical`:
<details>

```
 identical  .
  conflict  .copier-answers.yml
 overwrite  .copier-answers.yml
 identical  LICENSE
 identical  test.yaml
  conflict  tasks.py
 overwrite  tasks.py
  conflict  setup-devel.yaml
 overwrite  setup-devel.yaml
 identical  prod.yaml
 identical  odoo
 identical  odoo/custom
 identical  odoo/custom/ssh
 identical  odoo/custom/ssh/known_hosts
 identical  odoo/custom/ssh/id_rsa.pub
 identical  odoo/custom/ssh/id_rsa
 identical  odoo/custom/ssh/config
 identical  odoo/custom/src
 identical  odoo/custom/src/repos.yaml
 identical  odoo/custom/src/private
 identical  odoo/custom/src/private/.editorconfig
 identical  odoo/custom/src/addons.yaml
 identical  odoo/custom/entrypoint.d
 identical  odoo/custom/entrypoint.d/.empty
 identical  odoo/custom/dependencies
  conflict  odoo/custom/dependencies/pip.txt
      skip  odoo/custom/dependencies/pip.txt
 identical  odoo/custom/dependencies/npm.txt
 identical  odoo/custom/dependencies/gem.txt
 identical  odoo/custom/dependencies/apt_build.txt
 identical  odoo/custom/dependencies/apt.txt
 identical  odoo/custom/conf.d
 identical  odoo/custom/conf.d/.empty
 identical  odoo/custom/build.d
 identical  odoo/custom/build.d/.empty
 identical  odoo/Dockerfile
 identical  odoo/.dockerignore
  conflict  devel.yaml
 overwrite  devel.yaml
  conflict  common.yaml
 overwrite  common.yaml
  conflict  README.md
 overwrite  README.md
 identical  .vscode
 identical  .vscode/extensions.json
 identical  .vscode/doodba.code-snippets
  conflict  .pylintrc
 overwrite  .pylintrc
  conflict  .pylintrc-mandatory
 overwrite  .pylintrc-mandatory
 identical  .prettierrc.yml
  conflict  .pre-commit-config.yaml
 overwrite  .pre-commit-config.yaml
 identical  .isort.cfg
 identical  .gitignore
 identical  .flake8
 identical  .eslintrc.yml
 identical  .editorconfig
 identical  .docker
 identical  .docker/odoo.env
 identical  .docker/db-creation.env
 identical  .docker/db-access.env
```

</details>

**Expected behavior**

The 2 files should be deleted when updating

**Environment**
 - OS:  `Fedora SilverBlue 34`
 - Copier version:  `copier 6.0.0a7.post4.dev0+ec1a26c`
 - Python version: `3.9.6`
 - Installation method:  `pipx`

**Comment by defreng** [comment]
Hi guys,

I tried to get a better understanding of the way copier performs updates of existing 'template incarnations' - mainly to understand why files that are deleted in the template, aren't deleted in the incarnation...

I came up with the following picture, mostly by looking at the `run_update` function in https://github.com/copier-org/copier/blob/master/copier/main.py#L600 :
![image](https://user-images.githubusercontent.com/3579167/140661532-d0714564-add7-4d7f-9ff8-adc4f94de8e6.png)

Let me know if I made any mistakes in there...

Now, because the update happens using a copy operation (instead of utilizing a diff that was made on the template side, from △a and △b), files that were deleted in the template are simply overlooked. Because they still exist in the incarnation directory, and are not being overwritten with anything coming from the latest template commit.

As a possible solution for this, I was imagining a process more like the following:
![image](https://user-images.githubusercontent.com/3579167/140661743-fdbff6e2-6d14-420f-862b-c1377c26144d.png)

@Yajo, what do you think about this?

Probably, it would be a good idea to even go further, and never _disconnect_ the template and incarnation repositories - but instead just treat every incarnation as a branch of the template. I.e. not applying these updates as 'patches' on the incarnation repository. But instead, just doing a real Git 'merge' operation. Which would help to prevent having to manually solve the same conflicts over and over again.

I guess that would be a pretty substantial refactoring of copier, though.

**Comment by Yajo** [comment]
The algorithm is a bit complex, I think the clearest explanation can be found in https://copier.readthedocs.io/en/latest/updating/#how-the-update-works (apart from the source code, of course 😆).

You need to take into account 1) how the current state of the project compares with the latest incarnation, because user might have modified files, and that's a valid usage. Also you need to take current answers and compare 2) how the template would have been rendered with the previous version and 3) the new version using those particular answers, because the evolution of the template is not important (you have git for that). Instead, the important thing is the evolution of the incarnations given a set of answers for the template.

Then, once we have those 3 artifacts, we just apply some logic to merge them in the most expected way, keeping in mind that while doing a `copier update` the user might be providing some new answers and updating the template version all in one shot, and that the new version of the template might be adding or removing some questions.

So, I don't think there's anything here to refactor 😃 (again... all was refactored for the upcoming v6). The algorithm has a bug, probably in that last step, that simply has to be tested and fixed.

Thanks for your interest in Copier! If you want further details about the algorithms or implementations, or want to propose some refactors, that's OK, but please open a discussion instead, so we can keep this conversation focused on the bug.

**Comment by sabard** [comment]
I seem to have run into the same bug when updating from a dirty template and after further investigation, it doesn't look like any files are being removed on update—even those not using any templating logic. 

Does there need to be a separate manual step to remove subproject files that are deleted in the template or should the render step be handling this somehow?

**Comment by Yajo** [comment]
It was supposed that this line would do it. The bug must be around the way
the diff is obtained or applied:

https://github.com/copier-org/copier/blob/ddf387b7cfbf6f457d34026bcbe7287445b28d60/copier/main.py#L693
