### ISSUE TITLE
Use squash-merging method for merging PRs

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#760]
Just a simple suggestion towards a cleaner Git history:

I think many projects these days have adopted the [squash-merging method](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) for merging PRs. Typically, a PR consists of a single logical change of the target branch. This means, when a PR is merged, the Git history of the target branch receives one additional commit, even though the PR might have several commits due to code review and/or iterative development. Currently, it seems PRs are merged with an additional merge commit which clutters the Git history and makes it harder to read. If squash-merging was used, the Git history would become cleaner.

What do you think?

**Comment by yajo** [comment]
I usually do rebase, squash or merge depending on the change itself.

For example, if some contributor didn't write a proper commitizen message, I squash it just to reword it.

In the case of your recent https://github.com/copier-org/copier/pull/755, I would have used squash, but I used merge, I don't know why. Possibly for doing too many things in parallel 😆 

If the PR is properly structured in commits, I rebase or merge.

Just use some common sense, I don't think this needs to be an exact policy because each case can be different. Thanks for raising the subject though. 😊

**Comment by sisp** [comment]
Haha, sounds good. 👍 Thanks for the detailed explanation. 🙏
