### ISSUE TITLE
dirty changes not included when passing `-r HEAD`

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#787]
**Describe the problem**

I added a simple boolean question to my yaml

**Template**

```diff
author:
  type: str
  help: Author field for package.jsons
  default: Hypermedia App

email:
  type: str
  help: Email field for package.jsons
  default: no-reply@hypermedia.app

project_name:
  type: str
  help: Human-readable name
  default: Hypermedia App

app_name:
  type: str
  help: Short name (no spaces)
  default: '{{ project_name.lower().replace(" ", "-") }}'
+
+generate_ui:
+ type: bool
+ help: Should a web application be generated?

apis:
  type: yaml
  multiline: true
  default:
    - api
```

**To Reproduce**

1. Run `copier /path/to/local`
2. Question `generate_ui` never appears

**Expected behavior**

`generate_ui` should come after `app_name`

**Screenshots/screencasts/logs**

But it doesn't

```
➜  temp copier -a .copier-project.yaml /Users/tplus/projects/github/hydrofoil/creta-template-app ssz-view-builder
/Users/tplus/.local/pipx/venvs/copier/lib/python3.9/site-packages/copier/vcs.py:151: DirtyLocalWarning: Dirty template changes included automatically.
  warn(
🎤 Author field for package.jsons
   Hypermedia App
🎤 Email field for package.jsons
   no-reply@hypermedia.app
🎤 Human-readable name
   Hypermedia App
🎤 Short name (no spaces)
   hypermedia-app
🎤 apis (yaml)
    (Finish with 'Alt+Enter' or 'Esc then Enter')
> - api
```

**Environment**
 - OS: macOS
 - Copier version: 6.1.0
 - Python version: 3.9.5
 - Installation method: pipx

**Additional context**

Running from local path

**Comment by tpluscode** [comment]
Oh, I know 🤦 

Running from local (dirty or not) actually generates from the latest tag. It works with `-r, --vcs-ref` option but I kinda expected that generating from a local working dir template would actually take the current state of the repo

**Comment by yajo** [comment]
This is the expected behavior if you don't add that flag. The fact copier includes a temporary commit with your dirty changes doesn't mean it will use it if it's not selected. 

The only possible fix here is to improve the docs. Wanna do it yourself? 😃

**Comment by tpluscode** [comment]
Why not :)

So to clarify, because that’s not what I actually thought of. When I run with `—vcs-ref HEAD` from a repo with uncommitted changes, the HEAD will actually include those changes?

**Comment by yajo** [comment]
El mié, 7 de sep de 2022 a las 12:06:33 PM, Tomasz Pluskiewicz 
***@***.***> escribió:
> So to clarify, because that’s not what I actually thought of. When 
> I run with `—vcs-ref HEAD` from a repo with uncommitted changes, 
> the HEAD will actually include those changes?

Yes, that's it.

**Comment by tnarik** [comment]
I don't think this is correct, because if a `ref` is passed, then the code at https://github.com/copier-org/copier/blob/master/copier/vcs.py#L144-L163 is not executed and the "dirty files" are not added.

So, https://github.com/copier-org/copier/blob/master/copier/template.py#L438 doesn't execute, but the HEAD wouldn't contain the "dirty files". While NOT indicating HEAD will result in "dirty files" being added at https://github.com/copier-org/copier/blob/master/copier/vcs.py#L144-L163, but then ignored because the last tag is fetched.

At least that's what is happening on 6.2.0 to me, and that code didn't change on 7.x

**Comment by yajo** [comment]
Let me reopen then and review that later. Thanks!

**Comment by Maxinho96** [comment]
@yajo Same bug for me on macOS, version 7.0.1 installed with pipx.

**Comment by adepretis** [comment]
Also hitting this issue. Being new with copier (decided for it instead of Cookiecutter) it is a major PITA to get used to copier, playing around and developing the first templates when you have to do a local commit for each and every change. Would be really great if that could be fixed and copier supporting an efficient local development flow.
