### ISSUE TITLE
Support the providing of the config via pyproject.toml

### ISSUE THREAD

**Issue by adamcunnington-mlg** [copier-org/copier#873]
Firstly, cool project! I've just come across this project having used [cruft](https://github.com/cruft/cruft) (a wrapper around cookiecutter that supports updates) for years - but it's not well maintained.

Will you consider supporting the providing of the config via pyproject.toml given that's a defacto standard these days?

**Comment by pawamoy** [comment]
Copier is not a Python-only tool, so I highly doubt @yajo would agree to this. Besides, the config uses YAML features that do not exist in TOML.

**Comment by adamcunnington-mlg** [comment]
There are lots of tools implemented in python that are language agnostic in their usage but still support pyproject.toml in addition to other configuration file options.

Yes, the YAML to TOML is a bigger point but would be good to consider it fully. Pyproject.toml is a standard at this stage - a very great thing that avoids countless configuration files for many tools. In my dev workflow, I'm using a total of 21 tools and at this time, only 2 of them (incl. copier) does not support pyproject.toml. That was probably about 10 a year ago.

**Comment by pawamoy** [comment]
Could you show a few examples of these language agnostic tools that support configuration in pyproject.toml? It would be nice to how and why they support it.

My worry is that once you support a particular language's standards, users will ask for more (and maintenance capabilities are limited, as always): cargo.toml, package.json, etc. 

A probably realistic argument is that Copier is mainly used for Python projects, so we could at least support Python a bit more.

There's something I don't understand though: what is your use case exactly? Templates are generally not *also* Python projects, and inversely.

**Comment by adamcunnington-mlg** [comment]
Quick example of agnostic-tool with support; https://commitizen-tools.github.io/commitizen/config/

In my case, my template project contains a template python code that I want to test (e.g. tasks.py from python invoke).

**Comment by pawamoy** [comment]
I see, thanks, that makes sense.

**Comment by yajo** [comment]
Hi there! Thanks for your suggestion and welcome to the community!

Although I agree with you that storing config in a single place is very nice, it's not gonna happen here.

Apart from the reasons already explained in https://github.com/copier-org/copier/issues/873#issuecomment-1322070433,  it's because of another one. Copier template repositories usually are just that. It's not like pytest, commitizen, pylint, isort, black,  even poetry... those are just helpers for python projects. Copier instead is the main engine in a template project. In a Copier template, all those tools, and even python itself and the whole pyproject.toml are just helpers.

After all, you don't publish a pypi package out of a Copier template. 

So, this request would be more similar to asking to support embedding dockerfiles in pyproject.toml files. You can see there's a concept problem, apart from the technical challenge. 

Closing, but thanks anyway and keep around! ❤
