### ISSUE TITLE
Custom copier answers file doesn't work with updates

### ISSUE THREAD

**Issue by adamcunnington-mlg** [copier-org/copier#876]
I have customised my copier answer file to be called `.copier.yml`
When I go to do an update, i get the following error:

Cannot update because cannot obtain old template references from `.copier-answers.yml`.

If I am reading https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file and https://copier.readthedocs.io/en/stable/configuring/#answers_file correctly, you can customise this file name legitimately - but it looks like the logic that checks for the presence of this file is checking for a hardcoded file name

**Comment by yajo** [comment]
If you use a nonstandard answers file name, then you need to specify the answers file when updating the template.

Just do `copier -a .copier.yml update` and it'll work.

This is by design. When you're updating, Copier doesn't know which template you're updating, because [it supports applying more than one template to a single project](https://copier.readthedocs.io/en/stable/configuring/#applying-multiple-templates-to-the-same-subproject). Thus, if you say nothing, it will assume it's the default one (`.copier-answers.yml`).

Thanks for reporting, but I'll close because I don't think this is a bug. However, feel free to reopen if this still doesn't work for you.
