### ISSUE TITLE
Non-relative answers file

### ISSUE THREAD

**Issue by pwillis-eiq** [copier-org/copier#919]
**Is your feature request related to a problem? Please describe.**

I would like to generate templates on the fly via automation, such that I have a source template directory, and I generate the answers on the fly, then use copier to create the new destination copy.

Unfortunately the only way to do this (that I can see) is to:
1. copy the entire source template directory to a new temporary directory (which might involve a `git clone` if it's from git)
2. create the answers file in that new temporary directory
3. run copier to create the new copy
4. delete the old temporary directory

I can avoid almost all of this if I can just create the answers file and provide it to copier.

Unfortunately, the answers file can only be relative:

```
    with copier.Worker(src_path=src, dst_path=dst, answers_file=answersfn) as worker:
  File "pydantic/dataclasses.py", line 319, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    'order',
  File "pydantic/dataclasses.py", line 422, in pydantic.dataclasses._dataclass_validate_values
    if return_type is not MISSING:
pydantic.error_wrappers.ValidationError: 2 validation errors for Worker
src_path
  str type expected (type=type_error.str)
answers_file
  "/Users/myuser/temp-answers-1.yaml" is not a relative path (type=value_error.path.not_relative; path=/Users/myuser/temp-answers-1.yaml)
```

**Describe the solution you'd like**

Do not error if the file is a fully-qualified path and the file exists.

**Describe alternatives you've considered**

Script just to copy the entire template (including git clone), moving files around, running the copier command, removing temporary directory tree. Fairly annoying...

**Additional context**

I am using copier to generate a new Helm subchart for each new microservice I have (the charts all use a library, but with copier I can use Jinja2 and a yaml file to change the default values configured for each microservice).

**Comment by pawamoy** [comment]
I think you can pass your answers with the `data` argument instead of using an answers file.

**Comment by pwillis-eiq** [comment]
@pawamoy thank you for the suggestion, but that has its own drawbacks. it requires writing a custom script to pass all the values as command-line arguments. any user on a system can see the arguments being passed. there is a maximum limit to the size of arguments passed to programs (it's a fairly big limit, but still a limit). and i'm not sure how nested/complex data structures would be handled.

i think removing the restriction on relative-only paths would add useful functionality without imposing extra limitations

**Comment by pawamoy** [comment]
I meant the `data` parameter in the library itself. You do use Copier as a library right? You do not have to call the CLI.

**Comment by pwillis-eiq** [comment]
Oh, I tried writing it with Python, but when I couldn't get the answers file to work, I just switched to calling copier CLI from the shell script since it seemed I needed the workaround either way. I'll stick with the shell as it's easier to maintain shell scripts than Python (library interfaces aren't as stable as CLI interfaces)

**Comment by pawamoy** [comment]
To be clear, I was speaking about using `run_copy`: https://copier.readthedocs.io/en/stable/reference/main/#copier.main.run_copy. `data` is a dict, you can pass answers with it. Complex answers (like JSON can be passed as strings).

**Comment by yajo** [comment]
Hello and welcome to Copier! 🙌🏼 

I can see that there are 2 things here: one problem and one proposed solution. However, the solution you propose is not appropriate for the problem. Let me explain.

The answers file has only one single purpose of existence: being able to update a project. For copier to be able to update a project, it needs to replay the last update and compare it with the next update and the current state of the project. To replay the last update, it needs the last answers. Thus, the answers file must exist within the repo, or Copier won't be able to replay anything. All of this means that the answers file must exist in the same repo.

So, the proposed solution of being able to save answers files from elsewhere makes no sense from Copier's PoV. For this reason, I'm gonna close this issue.

Now, the real problem IIUC is that you want a comfortable way to pass answers to Copier. I understand that we're talking about new copies, not about updates (because in that case, answers recorded from last play are kept automatically and there's nothing to care about).

In this case, a valid solution would be to add a new CLI switch: `--data-file` that points to a YAML file that gets loaded as answers. That switch should probably be incompatible with the current `--data` switch (error if both are defined). The API call produced by the CLI app would be the same, as the only difference would be in the CLI.

If you think this would be a good solution, then please open a new issue about it so I can put it in the roadmap.

Thanks!

**Comment by pwillis-eiq** [comment]
> To replay the last update, it needs the last answers. Thus, the answers file must exist within the repo

Not if the user supplies the path to the answers file when copier is re-run. Or copier just looks up the answers somewhere outside the repo at runtime. Or another solution.

But, I get it. Like cookiecutter, the point of the project isn't to help the user solve their problem with a simple fix that has no downside. Rather the point of the project is to achieve some philosophical ideal of the authors.

Time to make another fork...

**Comment by yajo** [comment]
> Not if the user supplies the path to the answers file when copier is re-run. Or copier just looks up the answers somewhere outside the repo at runtime. Or another solution.

Yep, that's basically the same solution I just gave you with `--data-file`. it's just not the answers file as we know it, but instead a different way to provide answers from cli. Contrary to what you seem to be thinking, this solution is much simpler than yours and would solve your problem. 

If you want to publish the PR, it will get merged for sure if it stands up to our code quality. Go for it! 🙂
