### ISSUE TITLE
`poe lint` should be faster if user doesn't have nix installed

### ISSUE THREAD

**Issue by rafalkrupinski** [copier-org/copier#931]
The contributors documentation asks contributors to use `poe lint`:
https://github.com/copier-org/copier/blob/f8ae8d6e8ed8ec5333abe4b20ad53bc87123bff0/CONTRIBUTING.md?plain=1#L102

but it appears to be misconfigured

```shell
 % poe lint
Poe => pre-commit run --all-files
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
Check the log at /Users/matte/.cache/pre-commit/pre-commit.log
% ls .pre-commit-config.yaml
ls: .pre-commit-config.yaml: No such file or directory
```

**Comment by yajo** [comment]
Ah you were probably missing the previous steps: https://github.com/copier-org/copier/blob/f8ae8d6e8ed8ec5333abe4b20ad53bc87123bff0/CONTRIBUTING.md?plain=1#L59-L88

I switched to nix for the devshell not so long ago. Try it, it's quite nice!

**Comment by rafalkrupinski** [comment]
OK,
but it seems rather intrusive. Are you trying to scare away potential contributors? ;)
I mean I could understand a requirement to install `make`...

**Comment by rafalkrupinski** [comment]
Seriously there's no way I can start developing locally without **building** an operating system first?

**Comment by yajo** [comment]
AFAIK every binary is prebuilt and pushed to our public cache, which in
turn is enabled automatically when you follow the instructions, so you
should be just one command away from the same dev env I have. It does
download a lot, but it shouldn't build almost anything.

FWIW everybody downloads full OS images these days with docker. In nix it's
not much different, except that you download it package by package instead
of layer by layer.

Also I'm extremely tired of unpredictabilities in build and CI systems.
Particularly in pre-commit. For example I collected a lot of related
problems in the past in
https://github.com/OCA/oca-addons-repo-template/issues/175#issue-1466067857.
Since I switched to Nix, all of that simply disappeared (including Docker
😂).

Gitpod is also supported. Just click the button and get a web IDE ready to
code. It's compatible with Nix and Direnv out of the box.

I would love to have a smarter CI that not only yells about style but also
pushes back the reformatted code. I hope some day I have time to do it.

**Comment by rafalkrupinski** [comment]
> so you should be just one command away from the same dev env I have

Installing nix takes some time, building environment too. It took ca 1.5-2 hrs. But maybe I'm being picky - one command or three...

**Comment by yajo** [comment]
Really? Weird... In Gitpod takes about 1 minute to get you the dev env.

**Comment by rafalkrupinski** [comment]
I guess the cache didn't have macos binaries?

**Comment by yajo** [comment]
Could you please test with https://github.com/copier-org/copier/pull/980? It should let you go way faster if you have docker or podman installed.
