### ISSUE TITLE
Library use: allow resources as a template

### ISSUE THREAD

**Issue by rafalkrupinski** [copier-org/copier#933]
**Is your feature request related to a problem? Please describe.**

As a user of copier API, I'd like to store my template together with my project, similar to direct Jinja usage (`jinja.PackageLoader`).
The template and the code are tightly coupled so it would make the development easier.

**Describe the solution you'd like**

Copier could accept a special `resource:[project]:[path]` URI as the `src_path`.

Internally it could use `importlib.resources` (or `importlib_resources` backport project) to find and load template files. Version could be resolved with `importlib.metadata.version` (would require copier to know the distribution package - `[project]` part).

**Describe alternatives you've considered**

- Keeping template in a separate branch - doesn't really bring much from the developers perspective. It only helps keeping the template in the same repo. Needs some kind of versioning scheme.
- inferring `src_path` from `Path(__file__)` - would not work if my project is installed from wheel
- manually copying template from project to /tmp - looses versioning information and breaks `run_update`.
- Copier could be changed to accept a path within the repository - this partial solution would still require committing and pushing changes before testing `update`.

**Comment by yajo** [comment]
Hi again! Probably the solution for your problem is something you already said:



> Copier could be changed to accept a path within the repository

You can do this with `_subdirectory` already. See https://copier.readthedocs.io/en/stable/configuring/#subdirectory



> this partial solution would still require committing and pushing changes before testing `update`.

If your template is local and you use `vcs_ref="HEAD"`, [it will include local dirty changes automatically](https://copier.readthedocs.io/en/stable/generating/#templates-versions).

Or at least that's what it's supposed to do. It seems there's a bug there somewhere. Follow #787 for the fix. But fixing that issue is more scoped than this proposal.

Remember that Copier aims to be not much python-specific, so we can template all kinds of projects. At first sight your proposal will mean more python-specific stuff and probably more complexity around what are the assumptions we have currently on templates, so it's not very appealing to implement TBH.

I'll close this as there are no plans to implement, but feel free to continue discussing or even propose a prototype.

**Comment by rafalkrupinski** [comment]
Yeah, id does seem like the cost would outweigh the benefit. Abstracting VCS layer would allow copier to use other systems, like Mercurial, but... who cares really?

Thanks for the `_subdirectory` suggestion!

**Comment by yajo** [comment]
> Abstracting VCS layer would allow copier to use other systems, like Mercurial, but... who cares really?

That was the initial idea, but you're right. Everybody uses git, after all, so it still hasn't become a real need.
