### ISSUE TITLE
Document how to 'rebase' an existing project (not generated by template) on a copier template - and maybe add program support.

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#955]
I have a number of repositories which were created before I created a copier template based on those.
Now I would like to pretend that those repositories were created from the template.
All the boilerplate config files (e.g. settup.cfg, .pylintrx, pytest.init, noxfile.py, conftest.py, ...) are very similar, but have small variations besides those which would be made by the template expansion with different input.

One could:
1. Create a new project from the template
2. git init
3. Add all files
4. Commit
5. Copy all files from old project on top
6. Commit
**But this would loose history**

Or something like:
1. Make sure the working dir is clean (i.e. everythinf is commited or stashed)
7. Follow https://copier.readthedocs.io/en/stable/generating/#regenerating-a-project
8. Add new files (e.g. copier answers)
9. commit new and changed files
10. Add selected changes from previous version of overwritten files
Last step is the tricky one and possible a new subcommand could assist with the entire process.

**Comment by lhupfeldt** [comment]
Thank you for adding dockumetation, but I don't think it addresses the difficult step 5 mentioned above, you description simply overwrites existing files.

- Add selected changes from previous version of overwritten files
  Last step is the tricky one and possible a new subcommand could assist with the entire process.

**Comment by yajo** [comment]
The solution I always used for that problem is simply to use git to select the changes you want and discard the ones you don't. Git does an excellent job there, and with [git difftool](https://git-scm.com/docs/git-difftool) you can even use a dedicated diff solving software, so I don't have plans to do it in Copier with another subcommand.

However that doesn't mean the docs can't be improved! Please feel free to send a PR with better docs 😀
